<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "transition_tools"
 *
 * Auto generated by Extension Builder 2016-12-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Transition Tools',
	'description' => 'Tools to link up transition movements',
	'category' => 'plugin',
	'author' => 'Benno Flory',
	'author_email' => 'benno.flory@gmx.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);