<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "theme_default"
 *
 * Auto generated by Extension Builder 2016-04-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Default theme',
	'description' => 'Default theme',
	'category' => 'plugin',
	'author' => 'Markus Ohler',
	'author_email' => 'markus@webzeugs.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);